### PR TITLE
[create] RegistrationController and route

### PR DESCRIPTION
**Pull request by Muhammad235**

### CODE REVIEW

**Comment by Muhammad235** [comment]
@davydocsurg

**Comment by Muhammad235** [comment]
kindly review my pull request @davydocsurg

**Comment by davydocsurg** [comment]
> kindly review my pull request @davydocsurg

@Muhammad235 Which ticket is this PR for?

**Comment by Muhammad235** [comment]
I don't get what you mean, but it solves the issue #7

**Comment by davydocsurg** [comment]
> I don't get what you mean, but it solves the issue #7

@Muhammad235 The issue

**Comment by davydocsurg** [comment]
> > I don't get what you mean, but it solves the issue #7
> 
> @Muhammad235 I've closed this PR. The issue isn't linked to any ticket.

**Pull request closed without merging**
